apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: pod-with-node-affinity
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: nginx
      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: "node-role.kubernetes.io/control-plane"
               operator: Exists
