apiVersion: v1
kind: Pod
metadata:
  name: pod-with-tol
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8080

  tolerations:
  - key: "app"
    operator: "Equal"
    value: "blue"
    effect: "NoSchedule"
