apiVersion: v1
kind: Pod
metadata:
  name: pod-with-affinity-1
  labels:
    affnty: yeah
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 3030

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In
            values:
            - large
