apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay

spec:
  signerName: kubernetes.io/kube-apiserver-client
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - server auth
  request:
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXN5Y3ZJZWY3VWxMcGdMQXRlODVSeGN0SVFiSW9mWW84dkY0d0VuVXErNkFOCkJCQUNvZWZVYWs0bHdNQnhLUGRSSUZXb1U5MzlKVnIwQ1huWmFaUEdxdE9SSXEwM0Y2RHg4ZW1PRzdiMzZjOTUKSXFtZzdCU3JLK3dxWnhoTXN6aXlkTVdwRk5kS2p5aGxob2V0MzVFUmJxQVE3WlA1c1BXQnVHeVMzNlN2czdtQwo1YTMwbVRQdWNiU2g2TzFCTUNyWVpucHd2cnpGMm9LMFpycGZEcUFOWlhDZEFmUnVTVzZsekRPR1NqMGZkVkw3CisyVGxVRUp1aGd2KzZabkFsNzRwSHhCSlFSdElmVGFXSnMzRThJc002WmJPeWxYM3FsYUlKa0V6QnlXdFpSUGIKem1naThxK2JWYWEwR0VkaXZqUDNXYVgwNTdHLzdzQ3dPWkIwTk1XWWx3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSVdvQ3hXSm5nVFM2SU14YkVCY0tzcjJndlhQQWMwbCtQSFJ1RmxXdndwUHdJUWphWG5ECm1MZmNKUlZIWThUS3RhYjR5QSt1Z2pHN3hDaDNOYngxcEZVY29qTGV3dFNEeWVSUjdCUnlIR2xYSytkT01HaVMKWE1CbmlTZDlWdFZJUVBLUjMzRTk0Vkpja0V5NVFPQkVuZm96bXYvbC9pQnNHdmtkV0ZSNzJCZnpwcnlZeWJPeQo3dllsc1pWc3NaVVVURVZCRmEwdmxZeDhXdVJVZEVqYmZ1RGhZdlFSUUdKTW5vTTVMeDFjUnhNVjJkdHBnQVNZCktJQWlRTW1IZm1kQzN3NVhIY1hGYlZSNVpXNVQ1UllQdTZZRjcrNWdhZy9KRzM0QXdteC9aZld4S3FmdWpVQ3cKdlNkdmVYYTB3T3NqUUVybWxuMURvdDZWL2M5TjNZUDFaK1E9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
