apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-access

subjects:
  - kind: User
    name: michelle
    apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: Role
  name: node-access
  apiGroup: rbac.authorization.k8s.io
