apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-access
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - create
      - delete
      - watch
