apiVersion: v1
kind: Pod
metadata:
  name: nginx

spec:
  containers:
  - name: nginx
    image: nginx

    ports:
    - containerPort: 8080

    volumeMounts:
    - mountPath: /var/www/html
      name: my-pv

  volumes:
  - name: my-pv
    persistentVolumeClaim:
      claimName: my-pv
