apiVersion: v1
kind: Pod
metadata: 
  name: pod-with-pvc

spec: 
  containers:
  - name: nginx
    image: nginx

    volumeMounts:
      - name: data-vol
        mountPath: /data

  volumes:
  - name: data-vol
    persistentVolumeClaim:
      claimName: pvc1
