apiVersion: v1
kind: Pod
metadata:
  name: pod1

spec:
  containers:
  - name: nginx
    image: nginx

    ports:
    - containerPort: 8080

    volumeMounts:
    - name: logging-vol
      mountPath: /logs

  volumes:
  - name: logging-vol
    hostPath:
      path: /tmp
      type: Directory
