apiVersion: v1
kind: Pod
metadata:
  name: pod2

spec: 
  containers:
  - name: nginx
    image: nginx

    volumeMounts:
    - name: data-vol
      mountPath: /data

  volumes:
  - name: data-vol
    hostPath:
      path: /home/amroo/vols/pod2
      type: DirectoryOrCreate

