apiVersion: v1
kind: Service
metadata:
  name: app1-nodeport-svc
  labels:
    app: frontend-2
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30005
  selector:
    app: forntend-2
