apiVersion: v1
kind: ReplicationController
metadata:
  name: app-rc
  labels:
    app: frontend

spec:
  template:
    metadata:
      name: app
      labels:
        app: frontend

    spec:
      containers:
        - name: nginx-app
          image: nginx

  replicas: 3
